---

- name: add user to JunOS
  junipernetworks.junos.junos_user:
    name: "{{ net_username }}"
    state: "{{ net_user_state }}"
    role: "{{ net_user_role }}"
    encrypted_password: "{{ net_password_encrypted | default(omit) }}"
    sshkey: "{{ net_user_sshkey | default(omit) }}"
  tags: [user]